### PR TITLE
fix: Print scip-ruby version, not Sorbet version.

### LINKED ISSUE #127: Fix --version output
Right now, we just report the Sorbet version.

### PR DESCRIPTION
**Pull request by varungandhi-src**
### Motivation

Fixes #127.

### Test plan

Manually tested the output.

### CODE REVIEW

File: tools/scripts/publish-scip-ruby.sh [hunk 1]
```diff
@@ -0,0 +1,38 @@
+#!/usr/bin/env bash
+
+set -euo pipefail
+
+if [ -z "${NEW_VERSION:-}" ]; then
+  {
+    echo "error: Missing value for environment variable NEW_VERSION"
+    echo "hint: Invoke this scripts as NEW_VERSION=M.N.P ./tools/scripts/publish-scip-ruby.sh"
```
Comment (varungandhi-src) [inline tools/scripts/publish-scip-ruby.sh:8]:
```suggestion
    echo "hint: Invoke this script as NEW_VERSION=M.N.P ./tools/scripts/publish-scip-ruby.sh"
```
