### PR TITLE
fix: Add extra slash in URI for project root

### LINKED ISSUE #203: Records invalid `ProjectRoot`
### Input

_No response_

### Undesirable behavior

The functionality for the feature(s):
- Other: generated SCIP file

has undesirable behavior:
- Has incorrect information

in the following contexts that I've seen:
- Across functions within the same file

### Expected behavior

Generated `ProjectRoot` [File URI](https://en.wikipedia.org/wiki/File_URI_scheme) is missing one slash.

```
Metadata: &scip.Metadata{
    Version:  0,
    ToolInfo: &scip.ToolInfo{
      Name:      "scip-ruby",
      Version:   "0.5",
      Arguments: []string{
        "FIXME",
      },
    },
    ProjectRoot:          "file://data/s/gitlab-development-kit",
    TextDocumentEncoding: 1,
  },
```

https://github.com/sourcegraph/scip/issues/98#issuecomment-1641293020

### scip-ruby-debug indexing output

_No response_

### Configuration

```
✗ /data/s/scip-ruby --version
scip-ruby 0.3.8 git 797dae83e1b8419f14fb2c9944d4f0357b88a16d debug_symbols=true clean=1
Based on Sorbet 0.5 0f6fd90cdf20d507f20dcbe928431dc16d3e1793
```

### Additional info

The bug happens here.

https://github.com/sourcegraph/scip-ruby/blob/797dae83e1b8419f14fb2c9944d4f0357b88a16d/scip_indexer/SCIPIndexer.cc#L1278

### PR DESCRIPTION
**Pull request by varungandhi-src**
### Motivation

Fixes #203

### Test plan

n/a, it's simple enough

### CODE REVIEW

File: scip_indexer/SCIPIndexer.cc [hunk 1]
```diff
@@ -1275,7 +1275,7 @@ class SCIPSemanticExtension : public SemanticExtension {
         // NOTE: We are not respecting the path prefix option here. Should we do that?
         // FIXME(varun): filesystem::current_path() returns the path in 'native' format,
         // so this won't work on Windows.
-        metadata.set_project_root("file:/" + filesystem::current_path().string());
+        metadata.set_project_root("file://" + filesystem::current_path().string());
```
Comment (abitrolly) [inline scip_indexer/SCIPIndexer.cc:1278]: @varungandhi-src is the note above still actual?

Comment (varungandhi-src) [reply scip_indexer/SCIPIndexer.cc:1278]: Yes, it's still accurate. Sorbet has an extra flag `remove-path-prefix` which is not accounted for here.

Comment (abitrolly) [reply scip_indexer/SCIPIndexer.cc:1278]: So `scip-ruby` is broken on Windows? Not a big deal, just curious how C++ folks get around with that. Why ProjectRoot is URI at all and not a path?

Comment (varungandhi-src) [reply scip_indexer/SCIPIndexer.cc:1278]: > So scip-ruby is broken on Windows?

It's not supported on Windows. We haven't tried to build it on Windows, and there is no release binary for Windows.

> Not a big deal, just curious how C++ folks get around with that.

Could you be a bit more specific here? It isn't clear to me what you're asking...

> Why ProjectRoot is URI at all and not a path?

Windows paths can be in many different formats. Using a URI avoids downstream tooling having to deal with that.

Comment (abitrolly) [reply scip_indexer/SCIPIndexer.cc:1278]: > Could you be a bit more specific here? It isn't clear to me what you're asking...

How C++ folks are normalizing paths to be cross-platform.

Comment (varungandhi-src) [reply scip_indexer/SCIPIndexer.cc:1278]: > How C++ folks are normalizing paths to be cross-platform.

Generally it isn't an operation that makes sense, because the set of allowed characters in path components is different. E.g. you can have a backslash inside a component on Linux but not on Windows IIUC. There's also the question of case-sensitivity which varies across filesystems (not OSes).

If one really wants, one can use string replacement or similar based on what the exact requirements are...

Comment (varungandhi-src) [reply scip_indexer/SCIPIndexer.cc:1278]: That applies to most other fields of SCIP but not this one. For this particular field, it's not meant for the Sourcegraph backend, it's meant for any other tools in case the index is moved around/generated somewhere. E.g. the `scip snapshot` subcommand from the scip CLI can generate sources annotated with occurrence information -- it needs an absolute path to locate the source code.

Comment (abitrolly) [reply scip_indexer/SCIPIndexer.cc:1278]: Leaking absolute project paths may be a security issue. Maybe I am just paranoid.
